### ISSUE TITLE
Project task list

### ISSUE THREAD

**Issue by edwin7026** [edwin7026/py8085#3]
# Overview
This project is deemed to be a functional simulator of an 8085 microprocessor and also integrate a timing diagram, a UI to give a bird's eye view of all the activities going on at the architecture level.

# Tasks
- [x] Parser to parse assembly code
- [x] An assembler that converts mnemonics to instructions in binary
- [ ] Dump hex file associated with the assembly program
- [ ] 8085 core that executes the instructions
- [ ] Execution trace file
- [ ] Timing diagram viewer
- [ ] GUI to view architecture activities
